# Generated by Django 5.1.3 on 2024-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido del cliente: ')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del cliente: ')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección del cliente: ')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono del cliente: ')),
                ('email', models.CharField(max_length=50, verbose_name='Ingresar email: ')),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento: ')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
    ]
