# Generated by Django 5.1.3 on 2024-11-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto: ')),
                ('precio', models.DecimalField(decimal_places=2, help_text='ingresa valores con decimal', max_digits=10, verbose_name='Precio del producto: ')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimento', models.DateField()),
                ('cantidad_stock', models.IntegerField(verbose_name='Cantidad en stock')),
                ('marca', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
                ('caractersiticas_categoria', models.CharField(choices=[('Bebidas', 'Bebidas'), ('Comidas', 'Comidas'), ('Limpeza', 'Limpeza'), ('ropa', 'rospa'), ('Otros', 'Otros')], max_length=100)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
    ]
