# Generated by Django 5.1.3 on 2024-12-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0003_alter_productos_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_orden',
            name='estados',
        ),
        migrations.RemoveField(
            model_name='detalle_orden',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='detalle_orden',
            name='total',
        ),
        migrations.AddField(
            model_name='orden',
            name='estados',
            field=models.CharField(choices=[('VENDIDA', 'VENDIDA'), ('ANULADA', 'ANULADA')], default='VENDIDA', max_length=50),
        ),
        migrations.AddField(
            model_name='orden',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name=' Nombre del producto :'),
        ),
    ]
