# Generated by Django 5.1.3 on 2024-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0004_remove_detalle_orden_estados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_orden',
            options={'managed': True, 'verbose_name': 'Detalles de orden', 'verbose_name_plural': 'Detalles de orden'},
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotal_general',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
