# Generated by Django 5.1.3 on 2024-12-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0005_alter_detalle_orden_options_orden_subtotal_general'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={},
        ),
        migrations.AlterModelTable(
            name='orden',
            table=None,
        ),
    ]
