# Generated by Django 5.1.3 on 2024-12-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0006_alter_orden_options_alter_orden_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Orden'},
        ),
        migrations.AlterModelTable(
            name='orden',
            table='Orden',
        ),
    ]
