# Generated by Django 5.1.3 on 2024-12-10 20:03

import django.core.validators
import django.db.models.deletion
import nueva.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0008_metodopago_orden_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='marca',
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nueva.proveedores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ruc',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13), nueva.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='subtotal_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
