# Generated by Django 5.1.3 on 2024-12-10 20:05

import django.core.validators
import django.db.models.deletion
import nueva1.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10), nueva1.validadores.validacion_numeros])),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre del cliente : ')),
                ('apellido', models.CharField(max_length=50, validators=[nueva1.validadores.Validacion_letras])),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), nueva1.validadores.validacion_numeros])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'ingresa los datos del Cliente :',
                'verbose_name_plural': 'datos Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10), nueva1.validadores.validacion_numeros], verbose_name='Cedula del Empleado :')),
                ('nombre', models.CharField(max_length=50, validators=[nueva1.validadores.Validacion_letras], verbose_name='Nombre del Empleado : ')),
                ('apellido', models.CharField(max_length=50, validators=[nueva1.validadores.Validacion_letras])),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), nueva1.validadores.validacion_numeros])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Empleado :',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('ruc', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13), nueva1.validadores.validacion_numeros])),
                ('nombre', models.CharField(max_length=50, validators=[nueva1.validadores.Validacion_letras], verbose_name='Nombre de la empresa : ')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), nueva1.validadores.validacion_numeros])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa :',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA', 'TARJETA'), ('CHEQUE', 'CHEQUE'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=100, verbose_name='Método de Pago')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.PositiveBigIntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name=' Nombre del producto :')),
                ('caracteristicas_categoria', models.CharField(choices=[('Bebidas', 'Bebidas'), ('Comidas', 'Comidas'), ('Limpieza', 'Limpieza'), ('ropa', 'ropa'), ('Otros', 'Otros')], max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='ingresa valores con decimales', max_digits=10, verbose_name='Precio del producto : ')),
                ('cantidad_stock', models.IntegerField(verbose_name='Cantidad en stock : ')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Producto :',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('codigo_orden', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('estados', models.CharField(choices=[('VENDIDA', 'VENDIDA'), ('ANULADA', 'ANULADA')], default='VENDIDA', max_length=50)),
                ('subtotal_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nueva1.clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nueva1.empleados')),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nueva1.metodopago', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Orden',
                'db_table': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='Detalle_orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nueva1.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nueva1.productos')),
            ],
            options={
                'verbose_name': 'Detalles de orden',
                'verbose_name_plural': 'Detalles de orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('nombre', models.CharField(max_length=50, validators=[nueva1.validadores.Validacion_letras], verbose_name='Nombre del proveedor : ')),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10), nueva1.validadores.validacion_numeros])),
                ('apellido', models.CharField(max_length=50, validators=[nueva1.validadores.Validacion_letras])),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), nueva1.validadores.validacion_numeros])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nueva1.empresas')),
            ],
            options={
                'verbose_name': 'Proveedor ',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nueva1.proveedores'),
        ),
    ]
