# Generated by Django 5.1.3 on 2024-11-21 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practicasave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compras', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField(blank=True, default=0.0, editable=False, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicasave.producto')),
            ],
        ),
    ]
