# Generated by Django 5.1.3 on 2024-11-26 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practicasave', '0002_alter_factura_iva_alter_factura_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
